apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: monitors.k8mon.tpretz.com
spec:
  group: k8mon.tpretz.com
  names:
    kind: monitor
    plural: monitors
    shortNames:
    - mon
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                trigger:
                  type: string